# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = 'Modelo Caetê'
copyright = '2025, Modelo Caetê'
author = 'Modelo Caetê'
release = '1.0'

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration


import sphinx_rtd_theme

extensions = ['sphinx_rtd_theme']

# extensions = [
# #    'cloud_sptheme.ext.table_styling',
#     'sphinx_rtd_theme',
#     'sphinx.ext.todo',
#     'sphinx_carousel.carousel',
#     'sphinx_copybutton',
#     'sphinx_tabs.tabs',
#     # 'sphinxcontrib.bibtex',
#     'sphinx_toolbox.collapse',
#     'IPython.sphinxext.ipython_console_highlighting',
#     'IPython.sphinxext.ipython_directive',
# ]

# Paths that contain templates, relative to this directory.
templates_path = ['_templates']
exclude_patterns = []

# The language for content autogenerated by Sphinx.
language = 'en_UK'


# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = 'sphinx_rtd_theme'

# Caminho do logo que será exibido no canto superior esquerdo
html_logo = '_static/logo1.png'

# Caminho para arquivos estáticos (como imagens e CSS)
html_static_path = ['_static']

# Arquivo CSS adicional para personalizações visuais
html_css_files = ['custom.css']

html_theme_options = {
    'analytics_id': '',
    'logo_only': False,
    'prev_next_buttons_location': 'both',
    'style_external_links': True,
    'style_nav_header_background': 'white',
    # Toc options
    'collapse_navigation': True,
    'sticky_navigation': True,
    'navigation_depth': 4,
    'includehidden': True,
    'titles_only': False
}


# 🔧 CONFIGURAÇÃO PARA GITHUB PAGES:
html_baseurl = 'https://harmonize-brazil.github.io/'

html_title = 'LabTerra - Modelo CAETÊ'

html_context = {
    'display_github': True,
    'github_user': 'LabTerra',
    'github_repo': 'LabTerra.github.io',
    'last_updated': False,
    'conf_py_path': '/',
    #'commit': False,
}

html_show_sourcelink = False

html_favicon = './_static/favicon.png'

html_last_updated_fmt = '%b %d, %Y'

html_show_sphinx = False

html_search_language = 'en'

numfig = True

numfig_format = {
    'figure': 'Figure %s -',
    'table': 'Table %s -',
    'code-block': 'Code block %s -',
    'section': 'Section %s.'
}

math_eqref_format = 'Equation {number}'


# -- BibTex configuration ----------------------------------------------------

bibtex_default_style = 'plain' # 'plain', 'unsrtalpha', 'alpha'


# -- Copy button configuration -----------------------------------------------

copybutton_prompt_text = r'>>> |\.\.\. |\$ |In \[\d*\]: | {2,5}\.\.\.: | {5,8}: '
copybutton_prompt_is_regexp = True
#mathjax3_config = {'chtml': {'displayAlign': 'left'}}

exclude_patterns = []